// CONTENT PACK — the only place a product, a vendor or a person appears.
// Engine, HUD and mechanics are generic. `window.__ENGINE_CONTENT__`
// overrides this at load (see content-packs/README.md); the default pack
// exported here is also shipped as content-packs/tower/default.json.
export default {
  id: 'default',
  title: 'The Tower',
  version: '1.0.0',
  subtitle: 'Build the case for the chief operating officer.',
  situation: 'You ran discovery at a mid-size bank for Splunk Enterprise Security and SOAR. Now the chief operating officer (COO) wants your case, and she checks it from the bottom.',
  goal: 'Build five steps from the root cause up. Each needs a customer quote behind it and must lead to the step above.',
  ask: 'What is going wrong in our security operations, what does it lead to, and who answers for it to the board?',
  askHelp: 'Read your notebook first. The quotes tell one story. Build it from the bottom up.',
  exec: 'the chief operating officer',
  execShort: 'The COO',
  levels: [
    { id:'pain',   name:'Technical problem',   hint:'What is going wrong.' },
    { id:'op',     name:'What it causes',      hint:'What that leads to.' },
    { id:'metric', name:'Business number',     hint:'What that adds up to for the bank.' },
    { id:'expose', name:'What the board sees', hint:'How the board finds out.' },
    { id:'owner',  name:'Who owns it',         hint:'Who answers for it.' },
  ],
  evidence: [
    { id:'e6', code:'E6', who:'Head of internal audit',      short:'Audit head',      when:'Jan 22', where:'Audit readout',
      quote:'The examiner left two findings open. Both are about who can get into the payment systems. Neither one is about how we handle incidents.' },
    { id:'e7', code:'E7', who:'Chief of staff',              short:'Chief of staff',  when:'Mar 12', where:'Exec briefing',
      quote:'The board reads a resilience report every quarter. It lists every remediation review that is open, and directors have started asking how many there were this year.' },
    { id:'e2', code:'E2', who:'Head of security operations', short:'SecOps head',     when:'Mar 6',  where:'Discovery call',
      quote:'Our own number for mean time to resolve a confirmed intrusion is four hours ten minutes, averaged across the last two quarters.' },
    { id:'e8', code:'E8', who:'Chief of staff',              short:'Chief of staff',  when:'Mar 12', where:'Exec briefing',
      quote:'The chief information security officer owns the audit remediation plan. The chief operating officer owns the resilience report the board reads.' },
    { id:'e5', code:'E5', who:'Deputy chief financial officer', short:'Deputy CFO',   when:'Mar 11', where:'Email',
      quote:'Every late notification is a fixed penalty under the scheme rules, and it drops us into a remediation review we have to staff for a quarter.' },
    { id:'e1', code:'E1', who:'SOC shift lead',              short:'SOC shift lead',  when:'Mar 4',  where:'Discovery call',
      quote:'Last Tuesday my tier one queue had about three hundred alerts in it. The team worked forty one. The rest aged out at shift change.' },
    { id:'e3', code:'E3', who:'HR business partner',         short:'HR partner',      when:'Feb 27', where:'Follow-up call',
      quote:'We replaced three of our eight tier one analysts inside twelve months. Two of them said the same thing on the way out. All they ever did was triage.' },
    { id:'e4', code:'E4', who:'Head of financial crime risk', short:'Risk lead',      when:'Mar 6',  where:'Risk workshop',
      quote:'The card scheme gives us two hours from suspicion to notification. We went past that window twice last year.' },
  ],
  blocks: [
    // Level 0 — technical pain
    { id:'p2', level:0, claim:'Alert volume grows forty per cent a year', gist:'Volume up 40% a year', supports:[],
      pushback:'Nobody in this bank has ever told you that. Where did the number come from?',
      hold:'No customer quote gives a growth rate.' },
    { id:'p3', level:0, claim:'Confirming an intrusion takes over four hours', gist:'Four hours to confirm', supports:['e2'],
      pushback:'Over four hours by whose measure? My people quote me something else.',
      hold:'The head of security operations gave the number: 4 hours 10 minutes, averaged over two quarters.' },
    { id:'p1', level:0, claim:'Analysts work a fraction of the alerts they see', gist:'Alerts go unworked', supports:['e1'],
      pushback:'A fraction of what? Give me the two numbers or take the line off the slide.',
      hold:'The SOC shift lead counted it: 41 alerts worked out of about 300 in one shift.' },
    // Level 1 — operational consequence
    { id:'c3', level:1, claim:'Investigations run past the notification window', gist:'Window missed', supports:['e4'], follows:['p3'],
      pushback:'Which window, whose rule, and how many times did we go past it?',
      snap:'The window is about how long we take once we suspect something. The level below is not about time.',
      hold:'The financial crime risk lead said they have two hours to notify, and missed that twice last year.' },
    { id:'c1', level:1, claim:'Tier one analysts leave faster than we hire', gist:'Analysts walk out', supports:['e3'], follows:['p1'],
      pushback:'Turnover is high everywhere this year. Show me this is the work and not the market.',
      snap:'People leaving is real. The level below says nothing about the work they do all day.',
      hold:'The HR partner said three of eight analysts left within a year, and two said why.' },
    { id:'c2', level:1, claim:'Our tools do not share context with each other', gist:'Tools do not talk', supports:[], follows:['p1','p2','p3'],
      pushback:'That is a sentence about your product. It is not a sentence about my bank.',
      snap:'Nothing below this leads here, and no customer said it either.',
      hold:'No customer quote describes their tools.' },
    // Level 2 — business metric
    { id:'m2', level:2, claim:'Two findings on incident response are open', gist:'Two findings open', supports:[], follows:['c3'],
      pushback:'Those findings are about access to the payment systems. Audit will read this back to me line by line.',
      snap:'The findings are about access to the payment systems. The level below is not.',
      hold:'The audit head said the two open findings are about access to the payment systems, not incident response.' },
    { id:'m3', level:2, claim:'Customers leave after every published incident', gist:'Customers leave', supports:[], follows:['c1','c2','c3'],
      pushback:'We have never published one. So where does that sentence come from?',
      snap:'Nothing below this gets me to customers walking away.',
      hold:'No customer quote mentions customers leaving.' },
    { id:'m1', level:2, claim:'Each late notification carries a fixed penalty', gist:'Penalty per late report', supports:['e5'], follows:['c3'],
      pushback:'A penalty of what size, under what rule? Do not guess at that in this room.',
      snap:'A penalty follows a late notification. The level below is not a late notification.',
      hold:'The deputy CFO wrote that each late notification brings a fixed penalty and a review.' },
    // Level 3 — exposure the board sees
    { id:'x2', level:3, claim:'Open reviews are listed in the board resilience report', gist:'Board sees the review', supports:['e7'], follows:['m1'],
      pushback:'Does the board actually see these reviews, or is that what you assume? Who told you?',
      snap:'What reaches the board comes out of a penalty we can count. The level below is not one.',
      hold:'The chief of staff said the quarterly resilience report lists every open remediation review.' },
    { id:'x1', level:3, claim:'The open findings carry into the next examination', gist:'Findings go upstairs', supports:['e6'], follows:['m2'],
      pushback:'Name the findings, or this is a guess about my regulator.',
      snap:'Findings only carry forward if the level below is the findings. It is not.',
      hold:'The audit head said both findings are still open.' },
    { id:'x3', level:3, claim:'Our insurance reprices at the next renewal', gist:'Insurance reprices', supports:[], follows:['m1','m2','m3'],
      pushback:'Nobody here told you about insurance, and it is not in my remit.',
      snap:'Nothing below this gets us to an insurance renewal.',
      hold:'No customer quote mentions insurance.' },
    // Level 4 — executive owner
    { id:'o3', level:4, claim:'The CFO owns the penalty line', gist:'CFO owns the penalty', supports:[], follows:['x1','x2','x3'],
      pushback:'The CFO signs the penalty. That is not the same as owning the problem.',
      snap:'Nothing below this lands on his desk.',
      hold:'The deputy CFO described the penalty, not who owns it.' },
    { id:'o2', level:4, claim:'The CISO owns closing the audit findings', gist:'CISO owns the findings', supports:['e8'], follows:['x1'],
      pushback:'The CISO reports that plan to me. Owning it is a different sentence.',
      snap:'He owns the plan to fix the findings. The level below is not the findings.',
      hold:'The chief of staff said the CISO owns the audit remediation plan.' },
    { id:'o1', level:4, claim:'The COO owns the resilience report', gist:'COO owns the report', supports:['e8'], follows:['x2'],
      pushback:'You are putting this on a named person. Who told you it sits with her?',
      snap:'She owns a report. The level below is not about that report.',
      hold:'The chief of staff said the COO owns the resilience report the board reads.' },
  ],
};
