// Default content pack for engines/scale. Every learner-facing company, product,
// industry or count lives here — the engine and its mechanics stay generic.
// See content-packs/README.md for the pack contract.
export default {
  id: 'default',
  title: 'The Scale',
  version: '1.0.0',
  us:   { name:'Splunk',           short:'SPLUNK'  },
  them: { name:'Elastic Security', short:'ELASTIC' },
  // Setting words: who is buying, and what they are buying. Prose that names
  // the situation reads these instead of a hardcoded industry/product.
  industry: 'a regional bank',
  category: 'SIEM',
  // Credibility: starts full, every biased criterion you place drains it.
  cred: { start:100, perBias:6, threshold:60 },
  maxPlace: 5,
  swing: 12,               // bake-off margin that takes the score from even to the top
  // The criteria the customer already stated. They sit on their pan and always score.
  stated: [
    { id:'mttd',  stamp:'TIME TO DETECT', w:3, takes:'split',
      said:'Last quarter our median time to detect was 41 minutes. The board was told 15.',
      matters:'Their CISO already gave this number to the board.',
      note:'Both sides have a good answer here. Neither wins it outright.' },
    { id:'ramp',  stamp:'ANALYST RAMP', w:2, takes:'us',
      said:'Half of tier one quit this year. A new analyst needs about three months before I trust them.',
      matters:'Staff turnover is their real problem. Anything that speeds up training helps.',
      note:'Their current analysts already use your search language every day.' },
    { id:'rate',  stamp:'THREE-YEAR RATE', w:3, takes:'them',
      said:'Finance approved a number in March. It has not moved.',
      matters:'The budget is fixed. They will read this one literally.',
      note:'The other side has a lower list price and leads with it.' },
    { id:'audit', stamp:'AUDIT EVIDENCE', w:2, takes:'them',
      said:'In October the examiner asked for 13 months of search history. We had four.',
      matters:'A regulator already caught them short. This one has a deadline.',
      note:'The other side sells a compliance add-on that covers this.' },
  ],
  // The ten you could propose. `hears` is how it sounds to the customer when you say it out loud.
  candidates: [
    { id:'rba', stamp:'RISK ALERTING', w:3, bias:1, takes:'us', known:true,
      measures:'How many alerts one analyst works per shift, after related alerts are grouped.',
      hears:'A fair test. It names their real problem: too many alerts.',
      theirs:'Their risk scoring is set up rule by rule. Two of their references wrote their own.',
      say:'Ask them to count the alerts an analyst actually opens per shift. That number drives their turnover.' },
    { id:'migrate', stamp:'MIGRATION', w:2, bias:1, takes:'us', known:true,
      measures:'Engineer weeks to move current detections, dashboards and saved searches.',
      hears:'A fair test. Their last migration went badly, so they care.',
      theirs:'They offer a conversion tool. Their own notes say complex searches need rework by hand.',
      say:'They already worry about migration, so it does not sound like yours. Give a number for the rework, not a promise.' },
    { id:'archive', stamp:'ARCHIVE SEARCH', w:3, bias:2, takes:'us', known:true,
      measures:'Whether search can read data in object storage without loading it back first.',
      hears:'Close to your pitch. They have seen this line in a sales deck.',
      theirs:'They must reload archived data before they can search it. Their docs say that takes hours.',
      say:'Tie it to the examiner and the 13 months they could not produce. Then it is an audit question.' },
    { id:'automation', stamp:'AUTOMATION', w:2, bias:2, takes:'us', known:true,
      measures:'How many response actions the vendor maintains, so the customer does not write them.',
      hears:'Close to your pitch. They never asked for an integration count.',
      theirs:'Their integration list is short. Most of it is community maintained.',
      say:'Raise it only if they say they are short on engineers.' },
    { id:'cloudlogs', stamp:'CLOUD LOGS', w:2, bias:1, takes:'split', known:false,
      measures:'Whether cloud audit logs arrive without a custom connector.',
      hears:'A fair test. Half their new systems run in one cloud.',
      theirs:'Unknown. Assume they can do it.',
      say:'Both sides tie here. It is safe, but it does not change the result.' },
    { id:'sla', stamp:'SERVICE LEVEL', w:1, bias:0, takes:'split', known:false,
      measures:'The uptime the vendor will promise in the contract.',
      hears:'Their own words. Procurement wrote this one.',
      theirs:'Unknown.',
      say:'Low weight and a tie, so it is safe. It shows the list is fair.' },
    { id:'gb', stamp:'RATE PER GB', w:3, bias:0, takes:'them', known:true,
      measures:'List price per gigabyte of data brought in.',
      hears:'Their own words. Finance would add this without you.',
      theirs:'They are cheaper per gigabyte and lead with it in every deal.',
      say:'It sounds neutral, which makes it risky. It adds a heavy criterion they already win.' },
    { id:'latency', stamp:'DASH LATENCY', w:2, bias:1, takes:'them', known:true,
      measures:'Seconds from an event arriving to it showing on a dashboard.',
      hears:'A fair test. It sounds technical and neutral.',
      theirs:'A reference customer quoted under one second. They repeat it often.',
      say:'Neutral is not the same as good for you. They have a number ready for this one.' },
    { id:'agents', stamp:'AGENT COUNT', w:1, bias:3, takes:'us', known:false,
      measures:'How many machines have a data collector installed.',
      hears:'Straight off your data sheet. It is about you, not them.',
      theirs:'Unknown.',
      say:'Never propose this. It is light, and it shows you wrote the list.' },
    { id:'language', stamp:'QUERY LANGUAGE', w:2, bias:3, takes:'us', known:false,
      measures:'Which search language the test is run in.',
      hears:'Straight off your data sheet. Naming the language names the vendor.',
      theirs:'Unknown.',
      say:'Your edge is real, but they will not accept this one. Make the point through Analyst ramp instead.' },
  ],
};
